# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scrnify < Formula
  desc "Capture website screenshots and videos through the scrnify API"
  homepage "https://scrnify.com"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scrnify/scrnify-cli/releases/download/v0.1.0/scrnify_0.1.0_darwin_amd64.tar.gz"
      sha256 "6163afcacfe2e6130f224438e2e48ed95e2e3b6858d03b7b75f120bec58fa2cf"

      define_method(:install) do
        bin.install "scrnify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scrnify/scrnify-cli/releases/download/v0.1.0/scrnify_0.1.0_darwin_arm64.tar.gz"
      sha256 "a8e9534986ec20da90b596d2e96292d2fe683adff9bb69e0bdb887d07f1674f1"

      define_method(:install) do
        bin.install "scrnify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scrnify/scrnify-cli/releases/download/v0.1.0/scrnify_0.1.0_linux_amd64.tar.gz"
      sha256 "440baed23e8f6732ac4d4e5e019d04f59316d139373a7464d3cf464624aef4ae"
      define_method(:install) do
        bin.install "scrnify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scrnify/scrnify-cli/releases/download/v0.1.0/scrnify_0.1.0_linux_arm64.tar.gz"
      sha256 "4f57293059062f6484144eb4a0498f39ce3facaf3ecccbefeb1b7a8f18f8894c"
      define_method(:install) do
        bin.install "scrnify"
      end
    end
  end

  test do
    system "#{bin}/scrnify", "--version"
  end
end
